# https://github.com/cx-demo/cxflow-JavaVulnerableLab/blob/master/.github/workflows/checkmarx-cxflow-github-action.yml

name: checkmarx-cxflow-github-action

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env : #Set the environment variables for RepoName and PR number.
      REPO_NAME: ${{ github.event.repository.name }}
      BR_NAME: ${{ github.head_ref }} 
      PR_NUMBER: ${{ github.event.number }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Extract the short branch name
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
  
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
      #uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 
      with:    
        project: ${{ env.REPO_NAME }}-${{ steps.extract_branch.outputs.branch }}
        #project: 'GitHubWorkflowTest'
        #team: 'CxServer/SP/APJ'
        team: 'CxServer'
        #checkmarx_url: ${{ secrets.CHECKMARX_URL }}    
        #checkmarx_url: 'https://cxapactrial.checkmarx.net' 
        checkmarx_url: 'http://6b68ca1545db.ngrok.io'
        #checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_username: 'admin@cx.com' 
        #checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_password: 'Cx!123456'     
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        # Break build based on Checkmarx findings?
        
        # break_build: # optional
        incremental: false
        # Upload the Report for CodeQL/Security Alerts
        #- name: Upload SARIF file                     
        #  uses: github/codeql-action/upload-sarif@v1  
        #  with:
        #    sarif_file: cx.sarif
        # GitHub API Token (note: you don't have to create secrets.GITHUB_TOKEN, it is created automatically and will not appear in your repo's custom secrets)
      
        # Build the JavaVulnerableLab project
        #- name: Build with Maven
        #run: mvn -B package --file pom.xml
